### ISSUE TITLE
[Bug]: Cannot use custom API on safari

### ISSUE THREAD

**Issue by 9021007** [IzK-ArcOS/ArcOS-Frontend#112] opened 2024-01-04 06:59 UTC
### What happened?

I am trying to use my custom API endpoint, but it won't let me type in safari

https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/a995c3c2-c53b-4f5a-86ea-27cf699b438c

### Edition

Website

### If you are using a browser, which browsers are you seeing the problem on?

Safari

### Contact Detail(s)

@9021007

**Comment by ghost** [comment] 2024-01-04 07:03
is there any errors or something in devtools when u type?

**Comment by 9021007** [comment] 2024-01-04 07:06
Nope, nothing appears

https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/be30f7b1-ef36-4a72-92ad-ce8fd06e370d

**Comment by ghost** [comment] 2024-01-04 07:07
huh, this is weird

**Comment by IzKuipers** [comment] 2024-01-12 11:56
any plugins like grammarly or assistive typing installed?

**Comment by 9021007** [comment] 2024-01-12 11:58
I have Userscripts installed, but it's disabled so it shouldn't affect anything. That's all.

**Comment by IzKuipers** [comment] 2024-01-12 12:06
well a standard HTML input shouldn't get disabled by a browser

this isn't ArcOS. Nothing ArcOS does could cause this

**Comment by 9021007** [comment] 2024-01-12 12:07
Have you tried reproducing the issue?

**Comment by eversiege** [comment] 2024-01-12 12:07
Most of us don’t have a Mac to test issues on Safari

**Comment by IzKuipers** [comment] 2024-01-12 12:09
> Most of us don’t have a Mac to test issues on Safari

I'm at school but I can try to set up a MacOS KVM to try this bug out

**Comment by IzKuipers** [comment] 2024-01-12 12:10
But I know the ArcOS code better than anyone this can't be caused by anything I've written

**Comment by 9021007** [comment] 2024-01-12 12:17
I played around with it a bit more, if I tab into the text box, it'll let me type one letter and no more, and an autofill box appears with names from my contacts. 

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/12a4878d-4bd5-4826-a706-b18733800364)

**Comment by 9021007** [comment] 2024-01-12 12:20
ok well if you end up using a VM or whatever, I'm on macOS 12.5.1, safari version 15.6.1

**Comment by IzKuipers** [comment] 2024-01-12 13:25
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/fe627493-dd37-49f9-9bf6-66e575076581) then why does it work fine on this safari instance at my school

**Comment by 9021007** [comment] 2024-01-12 17:56
Well what safari version is it

**Comment by 9021007** [comment] 2024-01-12 17:56
to check: (In Menu Bar) Safari > About Safari

**Comment by 9021007** [comment] 2024-01-12 17:57
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/24487638/662d8434-39ca-4941-9825-1ac5ed262b22)
here are the currently supported/maintained macOS versions

**Comment by IzKuipers** [comment] 2024-01-12 20:03
> Well what safari version is it

Didn't have the time to check

**Comment by logangamesdaily** [comment] 2024-01-28 03:01
Can't reproduce, MacOS 14.2.1, Safari Version 17.2.1, MacBook Air M1. Can type perfectly fine.

**Comment by 9021007** [comment] 2024-01-28 03:02
> Can't reproduce, MacOS 14.2.1, Safari Version 17.2.1, MacBook Air M1. Can type perfectly fine.

As stated, this is occurring on macOS 12 and Safari 15.

**Comment by IzKuipers** [comment] 2024-02-19 09:12
Closing this as ArcOS v5 production is stopping as of February 20th 2024.

**Closed as not planned by IzKuipers** 2024-02-19 09:12 UTC
Labels: bug
