### ISSUE TITLE
Apps returning

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#85] opened 2023-09-07 10:58 UTC
if you reboot after removing an app the app just comes back

> References br$1119-247917-62632-862093

**Comment by IzKuipers** [comment] 2023-09-08 06:34
Can't currently reproduce :(

**Comment by IzKuipers** [comment] 2023-09-09 22:03
Closing as I can't reproduce this

**Closed as completed by IzKuipers** 2023-09-09 22:03 UTC
