### ISSUE TITLE
[Bug]: FTS test overlap when on License screen

### ISSUE THREAD

**Issue by eversiege** [IzK-ArcOS/ArcOS-Frontend#61] opened 2023-08-17 15:15 UTC
### What happened?

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/69052669/95969ca5-9436-47be-b900-22a8accc2dba)

### Edition

Website

### ArcOS Version

5.0.9

### If you are using a browser, which browsers are you seeing the problem on?

Chrome

### Other Browser(s)

Vivaldi (Chromium)

### Contact Detail(s)

eversiege (Discord)

**Comment by ghost** [comment] 2023-08-17 15:17
Didn't happen to me

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/72381315/5ec4ea64-9658-40b7-8c01-7cfc995ee746)

**NOTE:** It looked the same on the license screen as well

**Comment by IzKuipers** [comment] 2023-08-17 15:49
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/8a80ba58-c9eb-4665-b805-cb14c1a6e339)
I suppose this is the only way to further debug this issue

**Comment by IzKuipers** [comment] 2023-08-17 15:52
@eversiege Noticing cache mismatch: your web.izk-arcos.nl instance is not at all updated

**Comment by IzKuipers** [comment] 2023-08-17 15:53
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/51363b33-c244-43cf-a6f2-bcbe48480193)
closing: can't reproduce

**Closed as completed** 2023-08-17 15:53 UTC
Labels: bug
