### ISSUE TITLE
[Feature]: Make the Notes app

### ISSUE THREAD

**Issue by NikNikovsky** [IzK-ArcOS/ArcOS-Frontend#91] opened 2023-09-29 18:26 UTC
### Describe the new feature

It basically allows you to take quick notes, could be a desktop widget (and should probably have [this](https://github.com/IzK-ArcOS/ArcOS-Frontend/issues/56) built into it)

### Describe why the feature is useful

I personally think that it could make it more like a real OS

**Comment by eversiege** [comment] 2023-09-29 18:28
Duplicate of #68; not confirmed if the feature will be added or not. Mentioning @IzKuipers

**Comment by NikNikovsky** [comment] 2023-09-29 18:33
not expecting it to be done

**Comment by IzKuipers** [comment] 2023-09-29 18:37
Unfortunately no, this is because of an increased amount of stuff that has to be done, I'm simply too busy to finish it

(To DT: It is already in ArcOS Conceptual)

**Closed as not planned** 2023-10-19 17:41 UTC
Labels: enhancement
